trigger:
- main  # or your default branch

pool:
  vmImage: 'ubuntu-latest'  # Hosted agent

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'                 # Path to your pom.xml
    goals: 'clean install'                  # Build goal
    publishJUnitResults: true               # Enable test report publishing
    testResultsFiles: '**/surefire-reports/TEST-*.xml'  # Test result path
