trigger:
- master   # ✅ Use your actual branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@4
  displayName: 'Build and Test with Maven'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'

- task: PublishCodeCoverageResults@2
  displayName: 'Publish Code Coverage Results'
  inputs:
    codeCoverageTool: 'JaCoCo'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/jacoco.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/jacoco-html'
    failIfCoverageEmpty: true
