trigger:
- master  # or your default branch

pool:
  vmImage: 'ubuntu-latest'

stages:
# ---------- Stage 1: Build ----------
- stage: Build
  displayName: 'Build Maven Project'
  jobs:
  - job: MavenBuild
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean package'
        options: '-X'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        mavenVersionOption: 'Default'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'

    - task: PublishTestResults@2
      inputs:
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        failTaskOnFailedTests: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/target'
        ArtifactName: 'drop'
        publishLocation: 'Container'

# ---------- Stage 2: Deploy ----------
- stage: Deploy
  displayName: 'Deploy to Test Environment'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: DeployJob
    displayName: 'Deploy Artifact'
    steps:
    - download: current
      artifact: drop

    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'MyAzureConnection'      # Use your actual service connection name
        appName: 'webApp'                            # Use your actual App Service name
        package: '$(Pipeline.Workspace)/drop/*.jar'  # Make sure this JAR is valid for Web App
